default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV.fetch("DATABASE_URL", nil) %>
  username: <%= ENV.fetch("POSTGRES_USER", 'postgres') %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", nil) %>
  host: <%= ENV.fetch("POSTGRES_HOST", 'localhost') %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", 'shopify_ecommerce_development') %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DB", 'shopify_ecommerce_test') %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_PROD_DB", 'shopify_ecommerce_production') %>
