development:
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE', 'development-secret-key-base') %>

test:
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE', 'test-secret-key-base') %>

production:
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE') %>
